name: SQL Linter

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  SQLLinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code in Repository
        uses: actions/checkout@v4

      - name: Start SQL Linter
        run: |
          pip install sqlfluff
          sqlfluff lint DataSchema.sql --dialect postgres
